// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/code.proto

package code

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Input struct {
	Lang                 string   `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_4153a92670452c72, []int{0}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *Input) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Output struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_4153a92670452c72, []int{1}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Input)(nil), "code.Input")
	proto.RegisterType((*Output)(nil), "code.Output")
}

func init() { proto.RegisterFile("proto/code.proto", fileDescriptor_4153a92670452c72) }

var fileDescriptor_4153a92670452c72 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0x4f, 0x49, 0xd5, 0x03, 0x33, 0x85, 0x58, 0x40, 0x6c, 0x25, 0x7d, 0x2e,
	0x56, 0xcf, 0xbc, 0x82, 0xd2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0x9c, 0xc4, 0xbc, 0x74, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x1b, 0x24, 0x96, 0x94, 0x9f, 0x52, 0x29, 0xc1, 0x04, 0x11,
	0x03, 0xb1, 0x95, 0x14, 0xb8, 0xd8, 0xfc, 0x4b, 0x4b, 0x40, 0x3a, 0xc4, 0xb8, 0xd8, 0x8a, 0x52,
	0x8b, 0x4b, 0x73, 0x4a, 0xa0, 0x7a, 0xa0, 0x3c, 0x23, 0x0b, 0x2e, 0x3e, 0xe7, 0xfc, 0xdc, 0x82,
	0xcc, 0x9c, 0xd4, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x35, 0x2e, 0x76, 0xa8, 0x88,
	0x10, 0xb7, 0x1e, 0xd8, 0x09, 0x60, 0x3b, 0xa5, 0x78, 0x20, 0x1c, 0x88, 0x79, 0x4a, 0x0c, 0x49,
	0x6c, 0x60, 0x97, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x51, 0x56, 0x6e, 0x59, 0xad, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CompileServiceClient is the client API for CompileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CompileServiceClient interface {
	Compile(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error)
}

type compileServiceClient struct {
	cc *grpc.ClientConn
}

func NewCompileServiceClient(cc *grpc.ClientConn) CompileServiceClient {
	return &compileServiceClient{cc}
}

func (c *compileServiceClient) Compile(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error) {
	out := new(Output)
	err := c.cc.Invoke(ctx, "/code.CompileService/Compile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompileServiceServer is the server API for CompileService service.
type CompileServiceServer interface {
	Compile(context.Context, *Input) (*Output, error)
}

// UnimplementedCompileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCompileServiceServer struct {
}

func (*UnimplementedCompileServiceServer) Compile(ctx context.Context, req *Input) (*Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compile not implemented")
}

func RegisterCompileServiceServer(s *grpc.Server, srv CompileServiceServer) {
	s.RegisterService(&_CompileService_serviceDesc, srv)
}

func _CompileService_Compile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompileServiceServer).Compile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/code.CompileService/Compile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompileServiceServer).Compile(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

var _CompileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "code.CompileService",
	HandlerType: (*CompileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compile",
			Handler:    _CompileService_Compile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/code.proto",
}
